// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"login-form\"><label for=\"username\">Felhasználónév</label> <input type=\"text\" placeholder=\"Felhasználónév\" id=\"username\" name=\"username\"> <label for=\"password\">Jelszó</label> <input type=\"password\" placeholder=\"Jelszó\" id=\"password\" name=\"password\"> <button hx-post=\"/login\" hx-target=\"#result\" hx-swap=\"innerHTML\">Bejelentkezés</button> <button hx-get=\"/register\" hx-swap=\"outerHTML\" hx-target=\"#login-form\" type=\"button\">Regisztráció</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

/*
Regisztráció
Már létezik felhasználó ezzel a névvel!
Hibás Felhasználónév vagy jelszó!
Nem létezik felhasználó ezzel a névvel!
*/

var _ = templruntime.GeneratedTemplate
